var hierarchy =
[
    [ "ncpp::utilities::a_lref_t< type__ >", "structncpp_1_1utilities_1_1a__lref__t.html", null ],
    [ "ncpp::utilities::allocator_deleter_t< allocator_type__ >", "structncpp_1_1utilities_1_1allocator__deleter__t.html", null ],
    [ "ncpp::containers::cfv_queue_t< item_type__, allocator_type__ >", "classncpp_1_1containers_1_1cfv__queue__t.html", null ],
    [ "ncpp::static_warning_helper::false_type", "structncpp_1_1static__warning__helper_1_1false__type.html", [
      [ "ncpp::static_warning_helper::converter< 0 >", "structncpp_1_1static__warning__helper_1_1converter_3_010_01_4.html", null ]
    ] ],
    [ "ncpp::containers::fixed_vector_queue_t< item_type__, allocator_type__ >", "classncpp_1_1containers_1_1fixed__vector__queue__t.html", null ],
    [ "ncpp::containers::fixed_vector_stack_t< item_type__, allocator_type__ >", "classncpp_1_1containers_1_1fixed__vector__stack__t.html", null ],
    [ "ncpp::containers::fls_vector_t< item_type__, allocator_type__ >", "classncpp_1_1containers_1_1fls__vector__t.html", null ],
    [ "ncpp::containers::fls_vector_t< cell_type, cell_allocator_type >", "classncpp_1_1containers_1_1fls__vector__t.html", null ],
    [ "ncpp::containers::fls_vector_t< id_type, id_allocator_type >", "classncpp_1_1containers_1_1fls__vector__t.html", null ],
    [ "ncpp::utilities::function_traits_t< function_type__ >", "structncpp_1_1utilities_1_1function__traits__t.html", null ],
    [ "ncpp::utilities::function_traits_t< return_type__(arg_types__...)>", "structncpp_1_1utilities_1_1function__traits__t_3_01return__type_____07arg__types_____8_8_8_08_4.html", null ],
    [ "ncpp::containers::handle_map_t< item_type__, id_allocator_type__, cell_allocator_type__ >", "classncpp_1_1containers_1_1handle__map__t.html", null ],
    [ "ncpp::containers::handle_map_t< category_type, category_id_allocator_type, category_cell_allocator_type >", "classncpp_1_1containers_1_1handle__map__t.html", null ],
    [ "ncpp::in_pool_list", "structncpp_1_1in__pool__list.html", null ],
    [ "ncpp::in_stack_list", "structncpp_1_1in__stack__list.html", null ],
    [ "ncpp::utilities::is_function_t< type__ >", "structncpp_1_1utilities_1_1is__function__t.html", null ],
    [ "ncpp::utilities::is_function_t< return_type__(arg_types__...)>", "structncpp_1_1utilities_1_1is__function__t_3_01return__type_____07arg__types_____8_8_8_08_4.html", null ],
    [ "ncpp::utilities::is_istreamable_t< stream_type__, type__ >", "classncpp_1_1utilities_1_1is__istreamable__t.html", null ],
    [ "ncpp::utilities::is_ostreamable_t< stream_type__, type__ >", "classncpp_1_1utilities_1_1is__ostreamable__t.html", null ],
    [ "ncpp::pac::win_thread::main_thread_creation_placeholder", "structncpp_1_1pac_1_1win__thread_1_1main__thread__creation__placeholder.html", null ],
    [ "ncpp::utilities::na_lref_t< type__ >", "structncpp_1_1utilities_1_1na__lref__t.html", null ],
    [ "ncpp::native_allocator_i", "classncpp_1_1native__allocator__i.html", [
      [ "ncpp::native_allocator_t< value_type__ >", "classncpp_1_1native__allocator__t.html", [
        [ "ncpp::aligned_allocator_t< value_type__ >", "classncpp_1_1aligned__allocator__t.html", null ],
        [ "ncpp::crt_allocator_t< value_type__ >", "classncpp_1_1crt__allocator__t.html", null ],
        [ "ncpp::pool_allocator_t< value_type__, pool_heap_type__ >", "classncpp_1_1pool__allocator__t.html", null ],
        [ "ncpp::stack_allocator_t< value_type__, stack_heap_type__ >", "classncpp_1_1stack__allocator__t.html", null ],
        [ "ncpp::tgh_allocator_t< value_type__, tagged_heap_type__ >", "classncpp_1_1tgh__allocator__t.html", null ]
      ] ]
    ] ],
    [ "ncpp::pac::native_froutine_t< type__, initial_suspend_mode__, final_suspend_mode__, yield_suspend_mode__ >", "classncpp_1_1pac_1_1native__froutine__t.html", null ],
    [ "ncpp::native_heap", "classncpp_1_1native__heap.html", [
      [ "ncpp::pool_heap_t< object_type__, allocator_type__, lock_type__ >", "classncpp_1_1pool__heap__t.html", null ],
      [ "ncpp::stack_heap_t< allocator_type__, lock_type__ >", "classncpp_1_1stack__heap__t.html", null ],
      [ "ncpp::tagged_heap_t< allocator_type__, category_cell_allocator_type__, category_id_allocator_type__ >", "classncpp_1_1tagged__heap__t.html", null ]
    ] ],
    [ "ncpp::native_mem_janitor", "classncpp_1_1native__mem__janitor.html", [
      [ "ncpp::native_mem_auto_janitor_t< allocator_type >", "classncpp_1_1native__mem__auto__janitor__t.html", null ]
    ] ],
    [ "ncpp::pac::nonelock", "classncpp_1_1pac_1_1nonelock.html", null ],
    [ "ncpp::utilities::nth___template_arg_helper::nth_template_arg_t< is_single__, is_nth__, nth_remain__, arg_types__ >", "structncpp_1_1utilities_1_1nth______template__arg__helper_1_1nth__template__arg__t.html", null ],
    [ "ncpp::utilities::nth_template_arg_t< nth__, arg_types__ >", "structncpp_1_1utilities_1_1nth__template__arg__t.html", null ],
    [ "ncpp::utilities::nth___template_arg_helper::nth_template_arg_t< false, false, nth_remain__, nth___arg_type__, rest__... >", "structncpp_1_1utilities_1_1nth______template__arg__helper_1_1nth__template__arg__t_3_01false_00_c8208263a3aec978f1ca3164796561c5.html", null ],
    [ "ncpp::utilities::nth___template_arg_helper::nth_template_arg_t< false, true, nth_remain__, nth___arg_type__, rest__... >", "structncpp_1_1utilities_1_1nth______template__arg__helper_1_1nth__template__arg__t_3_01false_00_ce353c11cec5505ee1fede3a4620556c.html", null ],
    [ "ncpp::utilities::nth___template_arg_helper::nth_template_arg_t< true, false, nth_remain__, arg_type__ >", "structncpp_1_1utilities_1_1nth______template__arg__helper_1_1nth__template__arg__t_3_01true_00_09232482ce5196c3559d9715463522d0b.html", null ],
    [ "ncpp::utilities::nth___template_arg_helper::nth_template_arg_t< true, true, nth_remain__, arg_type__ >", "structncpp_1_1utilities_1_1nth______template__arg__helper_1_1nth__template__arg__t_3_01true_00_0523edf53778c15dd73cd8748cc1aed37.html", null ],
    [ "ncpp::out_pool_list", "structncpp_1_1out__pool__list.html", null ],
    [ "ncpp::out_stack_list", "structncpp_1_1out__stack__list.html", null ],
    [ "ncpp::pool", "structncpp_1_1pool.html", null ],
    [ "ncpp::pool_allocation", "structncpp_1_1pool__allocation.html", null ],
    [ "ncpp::pool_allocation_list", "structncpp_1_1pool__allocation__list.html", null ],
    [ "ncpp::pool_chunk", "structncpp_1_1pool__chunk.html", null ],
    [ "ncpp::pool_chunk_list", "structncpp_1_1pool__chunk__list.html", null ],
    [ "ncpp::pool_group", "structncpp_1_1pool__group.html", null ],
    [ "ncpp::pac::native_froutine_t< type__, initial_suspend_mode__, final_suspend_mode__, yield_suspend_mode__ >::promise_type", "structncpp_1_1pac_1_1native__froutine__t_1_1promise__type.html", null ],
    [ "ncpp::aligned_allocator_t< value_type__ >::rebind< U >", "structncpp_1_1aligned__allocator__t_1_1rebind.html", null ],
    [ "ncpp::crt_allocator_t< value_type__ >::rebind< U >", "structncpp_1_1crt__allocator__t_1_1rebind.html", null ],
    [ "ncpp::native_allocator_t< value_type__ >::rebind< U >", "structncpp_1_1native__allocator__t_1_1rebind.html", null ],
    [ "ncpp::pool_allocator_t< value_type__, pool_heap_type__ >::rebind< U >", "structncpp_1_1pool__allocator__t_1_1rebind.html", null ],
    [ "ncpp::stack_allocator_t< value_type__, stack_heap_type__ >::rebind< U >", "structncpp_1_1stack__allocator__t_1_1rebind.html", null ],
    [ "ncpp::tgh_allocator_t< value_type__, tagged_heap_type__ >::rebind< U >", "structncpp_1_1tgh__allocator__t_1_1rebind.html", null ],
    [ "ncpp::utilities::replace_function_return_type_t< function_type__, new_return_type__ >", "structncpp_1_1utilities_1_1replace__function__return__type__t.html", null ],
    [ "ncpp::utilities::replace_function_return_type_t< org_return_type__(arg_types__...), new_return_type__ >", "structncpp_1_1utilities_1_1replace__function__return__type__t_3_01org__return__type_____07arg__t2943548a2ca8253d431759339b7e7117.html", null ],
    [ "ncpp::safe_istream_forwarder_t< stream_type__, type__, is_streamable__ >", "structncpp_1_1safe__istream__forwarder__t.html", null ],
    [ "ncpp::safe_istream_forwarder_t< stream_type__, type__, false >", "structncpp_1_1safe__istream__forwarder__t_3_01stream__type_____00_01type_____00_01false_01_4.html", null ],
    [ "ncpp::safe_istream_forwarder_t< stream_type__, type__, true >", "structncpp_1_1safe__istream__forwarder__t_3_01stream__type_____00_01type_____00_01true_01_4.html", null ],
    [ "ncpp::safe_ostream_forwarder_t< stream_type__, type__, is_streamable__ >", "structncpp_1_1safe__ostream__forwarder__t.html", null ],
    [ "ncpp::safe_ostream_forwarder_t< stream_type__, type__, false >", "structncpp_1_1safe__ostream__forwarder__t_3_01stream__type_____00_01type_____00_01false_01_4.html", null ],
    [ "ncpp::safe_ostream_forwarder_t< stream_type__, type__, true >", "structncpp_1_1safe__ostream__forwarder__t_3_01stream__type_____00_01type_____00_01true_01_4.html", null ],
    [ "ncpp::safe_ostream_with_tab_forwarder_t< stream_type__, input_type__, is_streamable__ >", "structncpp_1_1safe__ostream__with__tab__forwarder__t.html", null ],
    [ "ncpp::safe_ostream_with_tab_forwarder_t< stream_type__, input_type__, false >", "structncpp_1_1safe__ostream__with__tab__forwarder__t_3_01stream__type_____00_01input__type_____00_01false_01_4.html", null ],
    [ "ncpp::safe_ostream_with_tab_forwarder_t< stream_type__, input_type__, true >", "structncpp_1_1safe__ostream__with__tab__forwarder__t_3_01stream__type_____00_01input__type_____00_01true_01_4.html", null ],
    [ "ncpp::pac::semaphore_t< mutex_type__, cond_var__ >", "classncpp_1_1pac_1_1semaphore__t.html", null ],
    [ "ncpp::utilities::singleton_t< class__ >", "classncpp_1_1utilities_1_1singleton__t.html", null ],
    [ "ncpp::utilities::singleton_t< task_system >", "classncpp_1_1utilities_1_1singleton__t.html", [
      [ "ncpp::dop::task_system", "classncpp_1_1dop_1_1task__system.html", null ]
    ] ],
    [ "ncpp::pac::spinlock", "classncpp_1_1pac_1_1spinlock.html", null ],
    [ "ncpp::stack", "structncpp_1_1stack.html", null ],
    [ "ncpp::stack_allocation", "structncpp_1_1stack__allocation.html", null ],
    [ "ncpp::stack_allocation_list", "structncpp_1_1stack__allocation__list.html", null ],
    [ "ncpp::stack_chunk", "structncpp_1_1stack__chunk.html", null ],
    [ "ncpp::stack_chunk_list", "structncpp_1_1stack__chunk__list.html", null ],
    [ "ncpp::stack_group", "structncpp_1_1stack__group.html", null ],
    [ "ncpp::utilities::templated_for_helper::step_t< f_type_t__, is_end__, end__, index__, arg_types__ >", "structncpp_1_1utilities_1_1templated__for__helper_1_1step__t.html", null ],
    [ "ncpp::utilities::templated_for_helper::step_t< f_type_t__, false, end__, index__, arg_types__... >", "structncpp_1_1utilities_1_1templated__for__helper_1_1step__t_3_01f__type__t_____00_01false_00_01e803adec8ed1656356ae5bf1fe698db3.html", null ],
    [ "ncpp::utilities::templated_for_helper::step_t< f_type_t__, true, end__, index__, arg_types__... >", "structncpp_1_1utilities_1_1templated__for__helper_1_1step__t_3_01f__type__t_____00_01true_00_01eb921587f08bb3cb26bce416f152d073d.html", null ],
    [ "ncpp::tagged_heap_block", "structncpp_1_1tagged__heap__block.html", null ],
    [ "ncpp::tagged_heap_category_t< allocator_type__ >", "classncpp_1_1tagged__heap__category__t.html", null ],
    [ "ncpp::dop::task_system_settings", "structncpp_1_1dop_1_1task__system__settings.html", null ],
    [ "ncpp::static_warning_helper::true_type", "structncpp_1_1static__warning__helper_1_1true__type.html", [
      [ "ncpp::static_warning_helper::converter< test >", "structncpp_1_1static__warning__helper_1_1converter.html", null ]
    ] ],
    [ "ncpp::utilities::unique_lock_t< locker_class__ >", "classncpp_1_1utilities_1_1unique__lock__t.html", null ],
    [ "ncpp::pac::weaklock_t< string_type__ >", "classncpp_1_1pac_1_1weaklock__t.html", null ],
    [ "ncpp::pac::win_fiber", "classncpp_1_1pac_1_1win__fiber.html", null ],
    [ "ncpp::pac::win_thread", "classncpp_1_1pac_1_1win__thread.html", null ]
];